spring.datasource.url=jdbc:postgresql://onlineshop-db:5432/onlineshop
product.service.url=http://product-service:8081
cart.service.url=http://cart-service:8080
order.service.url=http://order-service:8082
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

# Keycloak Adapter (OIDC)
keycloak.realm=admin
keycloak.auth-server-url=http://keycloak:8080/
keycloak.resource=user-service
keycloak.credentials.secret=secret
keycloak.bearer-only=true

# Keycloak Admin Client
keycloak.admin.server-url=http://keycloak:8080/
keycloak.admin.realm=admin
keycloak.admin.client-id=admin-cli
keycloak.admin.password=admin
keycloak.admin.username=admin

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak:8080/realms/admin
logging.level.org.springframework.security=DEBUG