spring.datasource.url=jdbc:postgresql://localhost:5432/onlineshop
product.service.url=http://localhost:8081
cart.service.url=http://localhost:8080
order.service.url=http://localhost:8082
spring.datasource.username=postgres
spring.datasource.password=postgres

# Keycloak Adapter (OIDC)
keycloak.realm=YourRealm
keycloak.auth-server-url=http://localhost:8080/
keycloak.resource=user-service
keycloak.credentials.secret=secret
keycloak.bearer-only=true

# Keycloak Admin Client
keycloak.admin.server-url=http://localhost:8080/
keycloak.admin.realm=YourRealm
keycloak.admin.client-id=admin-cli
keycloak.admin.password=admin
keycloak.admin.username=admin

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/YourRealm
logging.level.org.springframework.security=DEBUG